### ISSUE TITLE
Implement URL shortener for invite members link

### ISSUE THREAD

**Issue by juliomerisio** [qwikens/planning-poker#36]
Problem: 
![CleanShot 2024-03-25 at 12 34 24@2x](https://github.com/qwikens/planning-poker/assets/48305450/a443d75a-cbbd-435a-a761-07e3876cb951)

The URL is too long, and some apps have a character limit.

expected: http://surl.li/rxnxx

**Comment by Amorim33** [comment]
Closing due to the new hybrid encryption approach
#40
